# Generated by Django 3.0.6 on 2020-06-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='blog',
            name='resources',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subTopics',
            field=models.TextField(max_length=4096),
        ),
    ]
