# Generated by Django 3.0.6 on 2020-07-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
