# Generated by Django 3.0.6 on 2020-08-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bookmark_discuss_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic')),
            ],
        ),
    ]
