# Generated by Django 3.0.6 on 2020-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.BooleanField(default=False),
        ),
    ]
