# Generated by Django 3.0.6 on 2021-01-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subTopics',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='overview',
            new_name='preRequisites',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='resources',
        ),
    ]
