# Generated by Django 3.0.6 on 2021-01-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210112_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='blogContent',
        ),
    ]
