# Generated by Django 3.0.6 on 2021-04-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210112_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='blog.Profile'),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
